name: Update Kaggle Solana Dataset

on:
      # Run every day at midnight (UTC) — adjust the schedule as needed
      schedule:
            - cron: "0 0 * * *"
      # Allows manual triggering via the "Actions" tab
      workflow_dispatch:

jobs:
      update-dataset:
            runs-on: ubuntu-latest

            steps:
                  - name: Check out repository
                    uses: actions/checkout@v3

                  - name: Set up Python
                    uses: actions/setup-python@v4
                    with:
                          python-version: "3.10" # Or your required version

                  - name: Install Poetry
                    run: pip install poetry

                  - name: Update Poetry lock file
                    run: poetry lock

                  - name: Install project dependencies
                    run: poetry install

                  - name: Setup Proxy
                    run: |
                          echo "Setting up proxy configuration..."
                          sudo apt-get update
                          sudo apt-get install -y tor privoxy
                          sudo bash -c 'cat >> /etc/privoxy/config << EOL
                          forward-socks5 / 127.0.0.1:9050 .
                          max-client-connections 256
                          keep-alive-timeout 5
                          socket-timeout 300
                          EOL'
                          sudo service tor start
                          sudo service privoxy start
                          curl --proxy http://127.0.0.1:8118 https://api.ipify.org || true
                          sleep 15  # Allow services to stabilize

                  - name: Run the dataset update script with retries
                    env:
                          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
                          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
                          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
                          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
                          HTTP_PROXY: "http://127.0.0.1:8118"
                          HTTPS_PROXY: "http://127.0.0.1:8118"
                    run: |
                          until poetry run python solana_dataset_kaggle_auto_updater/kaggle_update_solana.py; do
                            echo "Dataset update failed, retrying in 60 seconds..."
                            sleep 60
                          done
